import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Starting to seed database...');

  // 1. Clear existing data
  await prisma.savedUniversity.deleteMany();
  await prisma.recommendationCache.deleteMany();
  await prisma.refreshToken.deleteMany();
  await prisma.course.deleteMany();
  await prisma.tag.deleteMany();
  await prisma.university.deleteMany();

  // 2. Create Tags
  const tagCities = [
    'Munich',
    'Berlin',
    'Aachen',
    'Heidelberg',
    'Stuttgart',
    'Karlsruhe',
    'Hamburg',
    'Freiburg',
    'Tübingen',
    'Bonn',
    'Frankfurt',
    'Darmstadt',
  ];
  for (const city of tagCities) {
    await prisma.tag.upsert({
      where: { name: city },
      update: {},
      create: { name: city, category: 'CITY' },
    });
  }

  const tagTypes = ['PUBLIC', 'TECHNICAL', 'PRIVATE'];
  for (const type of tagTypes) {
    await prisma.tag.upsert({
      where: { name: type },
      update: {},
      create: { name: type, category: 'UNIVERSITY_TYPE' },
    });
  }

  // 3. Create Universities
  const uniData = [
    {
      name: 'Technical University of Munich (TUM)',
      city: 'Munich',
      state: 'Bavaria',
      type: 'TECHNICAL',
      foundedYear: 1868,
      description:
        "One of Europe's top universities. Committed to excellence in research and teaching, interdisciplinary education and the active promotion of promising young scientists.",
      websiteUrl: 'https://www.tum.de',
      ranking: 37,
      tuitionFeeEuros: 0,
      hasStudentDormitory: true,
      averageRentEuros: 850,
      courses: [
        {
          name: 'MSc Computer Science',
          degree: 'MASTER',
          field: 'CS',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.5,
          gpaMinimum: 2.5,
        },
        {
          name: 'MSc Data Engineering and Analytics',
          degree: 'MASTER',
          field: 'DATA_SCIENCE',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.5,
          gpaMinimum: 2.0,
        },
        {
          name: 'BSc Mechanical Engineering',
          degree: 'BACHELOR',
          field: 'ENGINEERING',
          language: 'GERMAN',
          durationSemesters: 6,
          creditPoints: 180,
          ieltsMinimum: null,
          gpaMinimum: null,
        },
      ],
    },
    {
      name: 'LMU Munich',
      city: 'Munich',
      state: 'Bavaria',
      type: 'PUBLIC',
      foundedYear: 1472,
      description:
        'Ludwig-Maximilians-Universität München is a leading research university in Europe.',
      websiteUrl: 'https://www.lmu.de',
      ranking: 59,
      tuitionFeeEuros: 0,
      hasStudentDormitory: true,
      averageRentEuros: 850,
      courses: [
        {
          name: 'MSc Data Science',
          degree: 'MASTER',
          field: 'DATA_SCIENCE',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 7.0,
          gpaMinimum: 1.5,
        },
        {
          name: 'MSc Management',
          degree: 'MASTER',
          field: 'BUSINESS',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.5,
          gpaMinimum: 2.0,
        },
        {
          name: 'MSc Physics',
          degree: 'MASTER',
          field: 'ENGINEERING',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.5,
          gpaMinimum: 2.5,
        },
      ],
    },
    {
      name: 'RWTH Aachen University',
      city: 'Aachen',
      state: 'North Rhine-Westphalia',
      type: 'TECHNICAL',
      foundedYear: 1870,
      description:
        'The largest technical university in Germany, known for its engineering programs.',
      websiteUrl: 'https://www.rwth-aachen.de',
      ranking: 106,
      tuitionFeeEuros: 0,
      hasStudentDormitory: true,
      averageRentEuros: 500,
      courses: [
        {
          name: 'MSc Automotive Engineering',
          degree: 'MASTER',
          field: 'ENGINEERING',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.0,
          gpaMinimum: 2.5,
        },
        {
          name: 'MSc Software Systems Engineering',
          degree: 'MASTER',
          field: 'CS',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.5,
          gpaMinimum: 2.5,
        },
        {
          name: 'BSc Computer Science',
          degree: 'BACHELOR',
          field: 'CS',
          language: 'GERMAN',
          durationSemesters: 6,
          creditPoints: 180,
          ieltsMinimum: null,
          gpaMinimum: null,
        },
      ],
    },
    {
      name: 'Heidelberg University',
      city: 'Heidelberg',
      state: 'Baden-Württemberg',
      type: 'PUBLIC',
      foundedYear: 1386,
      description: "Germany's oldest university, a leading research institution.",
      websiteUrl: 'https://www.uni-heidelberg.de',
      ranking: 87,
      tuitionFeeEuros: 1500,
      hasStudentDormitory: true,
      averageRentEuros: 600,
      courses: [
        {
          name: 'MSc Molecular Biosciences',
          degree: 'MASTER',
          field: 'MEDICINE',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.5,
          gpaMinimum: 2.0,
        },
        {
          name: 'MSc Scientific Computing',
          degree: 'MASTER',
          field: 'CS',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.5,
          gpaMinimum: 2.5,
        },
        {
          name: 'BSc Biosciences',
          degree: 'BACHELOR',
          field: 'MEDICINE',
          language: 'GERMAN',
          durationSemesters: 6,
          creditPoints: 180,
          ieltsMinimum: null,
          gpaMinimum: null,
        },
      ],
    },
    {
      name: 'Technical University of Berlin (TU Berlin)',
      city: 'Berlin',
      state: 'Berlin',
      type: 'TECHNICAL',
      foundedYear: 1879,
      description: 'A prestigious research institution in the German capital.',
      websiteUrl: 'https://www.tu.berlin',
      ranking: 154,
      tuitionFeeEuros: 0,
      hasStudentDormitory: true,
      averageRentEuros: 700,
      courses: [
        {
          name: 'MSc Computer Science',
          degree: 'MASTER',
          field: 'CS',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.5,
          gpaMinimum: 2.5,
        },
        {
          name: 'MSc Information Systems Management',
          degree: 'MASTER',
          field: 'BUSINESS',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.5,
          gpaMinimum: 2.5,
        },
        {
          name: 'BSc Engineering',
          degree: 'BACHELOR',
          field: 'ENGINEERING',
          language: 'GERMAN',
          durationSemesters: 6,
          creditPoints: 180,
          ieltsMinimum: null,
          gpaMinimum: null,
        },
      ],
    },
    {
      name: 'Humboldt University of Berlin',
      city: 'Berlin',
      state: 'Berlin',
      type: 'PUBLIC',
      foundedYear: 1810,
      description: 'A university in the central borough of Mitte in Berlin.',
      websiteUrl: 'https://www.hu-berlin.de',
      ranking: 120,
      tuitionFeeEuros: 0,
      hasStudentDormitory: true,
      averageRentEuros: 700,
      courses: [
        {
          name: 'MSc Economics',
          degree: 'MASTER',
          field: 'BUSINESS',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.5,
          gpaMinimum: 2.0,
        },
        {
          name: 'MSc Psychology',
          degree: 'MASTER',
          field: 'MEDICINE',
          language: 'GERMAN',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: null,
          gpaMinimum: 1.5,
        },
        {
          name: 'MSc Statistics',
          degree: 'MASTER',
          field: 'DATA_SCIENCE',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.5,
          gpaMinimum: 2.5,
        },
      ],
    },
    {
      name: 'Freie Universität Berlin',
      city: 'Berlin',
      state: 'Berlin',
      type: 'PUBLIC',
      foundedYear: 1948,
      description: 'One of the largest universities in Germany.',
      websiteUrl: 'https://www.fu-berlin.de',
      ranking: 98,
      tuitionFeeEuros: 0,
      hasStudentDormitory: true,
      averageRentEuros: 700,
      courses: [
        {
          name: 'MSc Data Science',
          degree: 'MASTER',
          field: 'DATA_SCIENCE',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.5,
          gpaMinimum: 2.0,
        },
        {
          name: 'MSc Finance, Accounting and Taxation',
          degree: 'MASTER',
          field: 'BUSINESS',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 7.0,
          gpaMinimum: 2.0,
        },
        {
          name: 'BSc Computer Science',
          degree: 'BACHELOR',
          field: 'CS',
          language: 'GERMAN',
          durationSemesters: 6,
          creditPoints: 180,
          ieltsMinimum: null,
          gpaMinimum: null,
        },
      ],
    },
    {
      name: 'University of Freiburg',
      city: 'Freiburg',
      state: 'Baden-Württemberg',
      type: 'PUBLIC',
      foundedYear: 1457,
      description: 'The fifth oldest university in Germany.',
      websiteUrl: 'https://www.uni-freiburg.de',
      ranking: 189,
      tuitionFeeEuros: 1500,
      hasStudentDormitory: true,
      averageRentEuros: 650,
      courses: [
        {
          name: 'MSc Computer Science',
          degree: 'MASTER',
          field: 'CS',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.5,
          gpaMinimum: 2.5,
        },
        {
          name: 'MSc Renewable Energy Engineering and Management',
          degree: 'MASTER',
          field: 'ENGINEERING',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.5,
          gpaMinimum: 2.5,
        },
        {
          name: 'MSc Economics',
          degree: 'MASTER',
          field: 'BUSINESS',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.5,
          gpaMinimum: 2.5,
        },
      ],
    },
    {
      name: 'Karlsruhe Institute of Technology (KIT)',
      city: 'Karlsruhe',
      state: 'Baden-Württemberg',
      type: 'TECHNICAL',
      foundedYear: 2009,
      description: 'A national research center of the Helmholtz Association.',
      websiteUrl: 'https://www.kit.edu',
      ranking: 119,
      tuitionFeeEuros: 1500,
      hasStudentDormitory: true,
      averageRentEuros: 550,
      courses: [
        {
          name: 'MSc Mechanical Engineering',
          degree: 'MASTER',
          field: 'ENGINEERING',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.5,
          gpaMinimum: 2.5,
        },
        {
          name: 'MSc Information Systems',
          degree: 'MASTER',
          field: 'CS',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.5,
          gpaMinimum: 2.5,
        },
        {
          name: 'BSc Physics',
          degree: 'BACHELOR',
          field: 'ENGINEERING',
          language: 'GERMAN',
          durationSemesters: 6,
          creditPoints: 180,
          ieltsMinimum: null,
          gpaMinimum: null,
        },
      ],
    },
    {
      name: 'University of Tübingen',
      city: 'Tübingen',
      state: 'Baden-Württemberg',
      type: 'PUBLIC',
      foundedYear: 1477,
      description: "One of Germany's most famous and oldest universities.",
      websiteUrl: 'https://www.uni-tuebingen.de',
      ranking: 213,
      tuitionFeeEuros: 1500,
      hasStudentDormitory: true,
      averageRentEuros: 600,
      courses: [
        {
          name: 'MSc Machine Learning',
          degree: 'MASTER',
          field: 'DATA_SCIENCE',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.5,
          gpaMinimum: 2.0,
        },
        {
          name: 'MSc Neurosciences',
          degree: 'MASTER',
          field: 'MEDICINE',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.5,
          gpaMinimum: 2.0,
        },
        {
          name: 'BSc Business Administration',
          degree: 'BACHELOR',
          field: 'BUSINESS',
          language: 'GERMAN',
          durationSemesters: 6,
          creditPoints: 180,
          ieltsMinimum: null,
          gpaMinimum: null,
        },
      ],
    },
    {
      name: 'University of Bonn',
      city: 'Bonn',
      state: 'North Rhine-Westphalia',
      type: 'PUBLIC',
      foundedYear: 1818,
      description: 'A public research university located in Bonn.',
      websiteUrl: 'https://www.uni-bonn.de',
      ranking: 239,
      tuitionFeeEuros: 0,
      hasStudentDormitory: true,
      averageRentEuros: 550,
      courses: [
        {
          name: 'MSc Computer Science',
          degree: 'MASTER',
          field: 'CS',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.0,
          gpaMinimum: 2.5,
        },
        {
          name: 'MSc Life Sciences',
          degree: 'MASTER',
          field: 'MEDICINE',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.5,
          gpaMinimum: 2.5,
        },
        {
          name: 'MSc Economics',
          degree: 'MASTER',
          field: 'BUSINESS',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.0,
          gpaMinimum: 2.5,
        },
      ],
    },
    {
      name: 'University of Stuttgart',
      city: 'Stuttgart',
      state: 'Baden-Württemberg',
      type: 'TECHNICAL',
      foundedYear: 1829,
      description: 'A leading technically oriented university in Germany.',
      websiteUrl: 'https://www.uni-stuttgart.de',
      ranking: 312,
      tuitionFeeEuros: 1500,
      hasStudentDormitory: true,
      averageRentEuros: 650,
      courses: [
        {
          name: 'MSc Computer Science',
          degree: 'MASTER',
          field: 'CS',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.5,
          gpaMinimum: 2.5,
        },
        {
          name: 'MSc Electrical Engineering',
          degree: 'MASTER',
          field: 'ENGINEERING',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.5,
          gpaMinimum: 2.5,
        },
        {
          name: 'BSc Software Engineering',
          degree: 'BACHELOR',
          field: 'CS',
          language: 'GERMAN',
          durationSemesters: 6,
          creditPoints: 180,
          ieltsMinimum: null,
          gpaMinimum: null,
        },
      ],
    },
    {
      name: 'University of Hamburg',
      city: 'Hamburg',
      state: 'Hamburg',
      type: 'PUBLIC',
      foundedYear: 1919,
      description: 'The largest institution for research and education in northern Germany.',
      websiteUrl: 'https://www.uni-hamburg.de',
      ranking: 205,
      tuitionFeeEuros: 0,
      hasStudentDormitory: true,
      averageRentEuros: 700,
      courses: [
        {
          name: 'MSc Business Administration',
          degree: 'MASTER',
          field: 'BUSINESS',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.5,
          gpaMinimum: 2.5,
        },
        {
          name: 'MSc Data Science',
          degree: 'MASTER',
          field: 'DATA_SCIENCE',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.5,
          gpaMinimum: 2.5,
        },
        {
          name: 'BSc Informatics',
          degree: 'BACHELOR',
          field: 'CS',
          language: 'GERMAN',
          durationSemesters: 6,
          creditPoints: 180,
          ieltsMinimum: null,
          gpaMinimum: null,
        },
      ],
    },
    {
      name: 'Goethe University Frankfurt',
      city: 'Frankfurt',
      state: 'Hesse',
      type: 'PUBLIC',
      foundedYear: 1914,
      description: 'A university located in the financial capital of Germany.',
      websiteUrl: 'https://www.goethe-university-frankfurt.de',
      ranking: 302,
      tuitionFeeEuros: 0,
      hasStudentDormitory: true,
      averageRentEuros: 750,
      courses: [
        {
          name: 'MSc Quantitative Finance',
          degree: 'MASTER',
          field: 'BUSINESS',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 7.0,
          gpaMinimum: 2.0,
        },
        {
          name: 'MSc Computer Science',
          degree: 'MASTER',
          field: 'CS',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.5,
          gpaMinimum: 2.5,
        },
        {
          name: 'BSc Economics',
          degree: 'BACHELOR',
          field: 'BUSINESS',
          language: 'GERMAN',
          durationSemesters: 6,
          creditPoints: 180,
          ieltsMinimum: null,
          gpaMinimum: null,
        },
      ],
    },
    {
      name: 'Darmstadt University of Technology (TU Darmstadt)',
      city: 'Darmstadt',
      state: 'Hesse',
      type: 'TECHNICAL',
      foundedYear: 1877,
      description: 'A leading technical university with a focus on engineering and IT.',
      websiteUrl: 'https://www.tu-darmstadt.de',
      ranking: 246,
      tuitionFeeEuros: 0,
      hasStudentDormitory: true,
      averageRentEuros: 550,
      courses: [
        {
          name: 'MSc Artificial Intelligence',
          degree: 'MASTER',
          field: 'DATA_SCIENCE',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.5,
          gpaMinimum: 2.0,
        },
        {
          name: 'MSc Distributed Software Systems',
          degree: 'MASTER',
          field: 'CS',
          language: 'ENGLISH',
          durationSemesters: 4,
          creditPoints: 120,
          ieltsMinimum: 6.5,
          gpaMinimum: 2.5,
        },
        {
          name: 'BSc Electrical Engineering',
          degree: 'BACHELOR',
          field: 'ENGINEERING',
          language: 'GERMAN',
          durationSemesters: 6,
          creditPoints: 180,
          ieltsMinimum: null,
          gpaMinimum: null,
        },
      ],
    },
  ];

  for (const uni of uniData) {
    const { courses, ...uniDetails } = uni;

    await prisma.university.create({
      data: {
        ...uniDetails,
        courses: {
          create: courses,
        },
        tags: {
          connect: [{ name: uniDetails.city }, { name: uniDetails.type }],
        },
      },
    });
  }

  console.log(`Seeded ${uniData.length} universities and their courses successfully!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
